version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - db.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-js
    env_file:
      - app.env
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    working_dir: '/app'
    command: sh -c 'npm i && nodemon'
    depends_on:
      - db
volumes:
  my-db:
    driver: local
