version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_name'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-js
    volumes:
      - ./backend_node:/backend_node
    ports:
      - 3000:3000
    working_dir: '/backend_node'
    command: sh -c 'npm i && nodemon'
    depends_on:
      - db
volumes:
  my-db:
    driver: local
